### ISSUE TITLE
override `github.actor` as Docker.io user

### ISSUE THREAD

**Issue by exaexa** [macbre/push-to-ghcr#14]
Hello,
is it somehow possible to use a different username for docker.io container pushes than what is hardcoded in `github.actor` here https://github.com/macbre/push-to-ghcr/blob/master/action.yml#L115 ?

(Possibly, it would be great to have a separate configuration variable for it.)

Thanks!

**Comment by macbre** [comment]
Sure, thanks for this suggestion!

**Comment by exaexa** [comment]
I see this implemented, will check out as soon as I get back to the CI settings again. Thanks a lot!
