### ISSUE TITLE
Lowercase github.actor for dockerhub

### ISSUE THREAD

**Issue by ClashTheBunny** [macbre/push-to-ghcr#20]
Dockerhub is case sensitive and I think it's always lowercase. This makes trouble here when trying to push with a github username with capitalization:

https://github.com/macbre/push-to-ghcr/blob/f8f1bc2d6398731d0392be8185713bf1c92c38ef/action.yml#L124

**Comment by macbre** [comment]
Thanks for reporting the issue, @ClashTheBunny!

#14 will cover it in a more general fashion allowing one to fully overwrite the actor.

**Comment by ClashTheBunny** [comment]
Yep, thanks so much!
