### ISSUE TITLE
Superfluous Docker Hub warning

### ISSUE THREAD

**Issue by kthy** [macbre/push-to-ghcr#21]
Every time I use this action I get a warning that the image wasn't uploaded to Docker Hub. Since I don't _want_ to upload the image to Docker Hub and I like to treat warnings as errors, it would be nice if there was a way to silence this warning.

**Comment by aflury** [comment]
It's still annoying to see this as a `notice` annotated on every run. I'd argue `debug` is more appropriate. Why would I care about something called `push-to-ghcr` _not_ pushing to `docker.io`, other than for debugging?
